version: "1.1"

services :
  short_url:
      image: postgres:16
      restart: always
      shm_size: 128mb
      environment:
        - POSTGRES_USER=admin
        - POSTGRES_PASSWORD=admin
        - POSTGRES_DB=short_db
      volumes:
        - ./data:/var/lib/postgresql/data
      ports:
        - "5432:5432"